version: '3.9'


services:
  backend:
    image: ${IMAGE_TAG}
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reverse_courses
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

