version: '3.9'


services:
  backend:
    image: ${IMAGE_TAG}
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reverse_courses
    ports:
      - "5432:5432"
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb


