version: '3.9'


services:
  backend:
    image: ${IMAGE_TAG}
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8888:8000"
  frontend:
    image: ${FRONTEND_IMAGE_TAG}
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reverse_courses
    ports:
      - "5432:5432"
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
  web:
    image: web:local
    build:
      dockerfile: web.Dockerfile
      context: .
    ports:
      - "8000:80"
    restart: always


