version: '3'

tasks:
  lint:
    cmds:
      - ruff format .
      - ruff check --fix .

  run:
    cmds:
      - docker compose up --build

  migration:
    cmds:
      -  docker exec reverse-courses-platform-backend-1 poetry run python -m alembic upgrade head

  make_migration-*:
    vars:
      MIGRATE_NAME: '{{index .MATCH 0}}'
    cmds:
      - docker exec reverse-courses-platform-backend-1 poetry run python -m alembic revision --autogenerate -m {{ .MIGRATE_NAME }}