version: '3'

tasks:
  lint:
    cmds:
      - ruff format .
      - ruff check --fix .

  migration:
    cmds:
      -  docker exec reverse_courses_platform-backend-1 poetry run python -m alembic upgrade head

  make_migration-*:
    vars:
      MIGRATE_NAME: '{{index .MATCH 0}}'
    cmds:
      - docker exec reverse_courses_platform-backend-1 poetry run python -m alembic revision --autogenerate -m {{ .MIGRATE_NAME }}