name: Docker Image CI [backend]

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  IMAGE_TAG: darius1223/reverse-courses:${{ vars.github.run_id }}
  DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN}}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --tag $IMAGE_TAG backend
    - name: Docker Login
      run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - name: Push to Docker registry
      run: docker push $IMAGE_TAG

  push:

    runs-on: ubuntu-latest

    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            echo '--- START WORK ON REMOTE SERVER ---';
            cd ${{ secrets.PROJECT_FOLDER }};
            echo '--- LIST OF FILES ---';
            ls -al;
            echo '--- GIT INFORMATION ---'
            git co dev;
            git pull;
            echo '--- DOCKER OPERATIONS ---';
            docker-compose down;
            echo '--- LIST OF DOCKER CONTAINERS AFTER STOPING DOCKER CONTAINERS ---';
            docker ps;
            docker-compose --file docker-compose.prod.yml up -d;
            docker system prune --all --force;
            echo '--- LIST OF DOCKER CONTAINERS AFTER STARTING DOCKER CONTAINERS ---';
            docker ps;
